# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/shivansh/cpre_4870/lab3/20250930_CPRE_Lab3/HW/cpre487-587-lab3-main/simple_interface/vivado/simple_interface/simple_interface.srcs/sources_1/bd/staged_mac_bd/ip/staged_mac_bd_axis_subset_converter_0_1/staged_mac_bd_axis_subset_converter_0_1.xci
# IP: The module: 'staged_mac_bd_axis_subset_converter_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/shivansh/cpre_4870/lab3/20250930_CPRE_Lab3/HW/cpre487-587-lab3-main/simple_interface/vivado/simple_interface/simple_interface.srcs/sources_1/bd/staged_mac_bd/ip/staged_mac_bd_axis_subset_converter_0_1/staged_mac_bd_axis_subset_converter_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'staged_mac_bd_axis_subset_converter_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/shivansh/cpre_4870/lab3/20250930_CPRE_Lab3/HW/cpre487-587-lab3-main/simple_interface/vivado/simple_interface/simple_interface.srcs/sources_1/bd/staged_mac_bd/ip/staged_mac_bd_axis_subset_converter_0_1/staged_mac_bd_axis_subset_converter_0_1.xci
# IP: The module: 'staged_mac_bd_axis_subset_converter_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/shivansh/cpre_4870/lab3/20250930_CPRE_Lab3/HW/cpre487-587-lab3-main/simple_interface/vivado/simple_interface/simple_interface.srcs/sources_1/bd/staged_mac_bd/ip/staged_mac_bd_axis_subset_converter_0_1/staged_mac_bd_axis_subset_converter_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'staged_mac_bd_axis_subset_converter_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
